service: visma-serverless-course-raivis

provider:
  name: aws
  runtime: python3.8
  region: eu-west-1
  stage: TEST
  versionFunctions: false
  apiGateway:
    apiKeys:
      - pipeKey

frameworkVersion: '3'

package:
  include:
   - "./src/**"
  exclude:
   - node_modules/**
   - venv/**

functions:
  hello_pipe:
    handler: src/handler.hello
    events:
      - http:
          path: /hello
          method: get
          private: true

  calculatorv2_pipe:
    handler: src/calculatorv2.lambda_handler
    events:
    - http:
        path: /calculatorv2
        method: post
        private: true