AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Region:
    Description: Region to be hosted in
    Type: String
    Default: eu-west-1

Resources:
  pipeArtifactBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: "sls-visma-course-artifact-bucket"
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

backendPipeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "backendPipelinePipelineCreator"
      AssumeRolePolicyDocument:
        Statement:
          - Action: [ 'sts:AssumeRole' ]
            Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: "backendPipelinePolicy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Action:
              - '*'
              Effect: Allow
              Resource: '*'